

package arrow.reflect.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link arrow.reflect.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/transformation")
@TestDataPath("$PROJECT_ROOT")
public class TransformationTestGenerated extends AbstractTransformationTest {
  @Test
  public void testAllFilesPresentInTransformation() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/transformation"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("hello_class_test.kt")
  public void testHello_class_test() {
    runTest("src/testData/transformation/hello_class_test.kt");
  }

  @Test
  @TestMetadata("increment_test.kt")
  public void testIncrement_test() {
    runTest("src/testData/transformation/increment_test.kt");
  }

  @Test
  @TestMetadata("product_test.kt")
  public void testProduct_test() {
    runTest("src/testData/transformation/product_test.kt");
  }
}
