package arrow.meta.quotes

import org.jetbrains.kotlin.GeneratedDeclarationKey

/**
 * Key for declarations generated by the quotes plugin
 */
object QuotesPluginKey : GeneratedDeclarationKey() {
    override fun toString(): String = "ArrowQuotesPluginKey"
}